### ISSUE TITLE
figure link missing at gis-oer/GISオープン教材/課題/課題_ラスタデータの分析.md

### ISSUE THREAD

**Issue by yshayakawa** [gis-oer/gis-oer#1]
"kadai" 
link to the figure is missing.

**Comment by yamauchi-inochu** [comment]
コメントが遅くなりすみません。該当箇所について、以下のように修正いたしました。

https://github.com/gis-oer/gis-oer/blob/master/GISオープン教材/課題/課題_ラスタデータの分析.md#数値標高モデルの視覚的分析
