### ISSUE TITLE
ライセンスの記述について

### ISSUE THREAD

**Issue by wata909** [gis-oer/gis-oer#2]
https://gis-oer.github.io/gitbook/book/

の右ウィンドに表示される「本教材では、一部で第3者が作成したソフトウェアやウェブサイト等のキャプチャー画像を 教育を目的とした公正な利用 という位置づけで、使用しております。」とありますが、誤解を招く表現だと思います。

著作権の「適法引用」の範囲であれば、どのような目的であっても引用することは可能です。
一方で、「教育を目的とした公正な利用」であったとしても、適法引用の条件を満たさなければ、引用を行うことはできません。

また、著作権法では、33条「教科用図書等への掲載」、34条「学校教育番組の放送等
」、35条「学校その他の教育機関における複製等」で、教育における著作権の制限が規定されていますが、インターネットでWeb公開する場合は、おそらく対象外になると考えられます。

そのため、ここは、

「本教材では、一部で第3者が作成したソフトウェアやウェブサイト等のキャプチャー画像を 著作法上許可されている引用に基づき、使用しております」

等の表現がよいかと考えられます。
今の記載方法ですと、「教育を目的とした公正な利用」であれば、著作権法上許可されない利用も、「教育目的であれば許される」という誤解を招くと思います。

修正、よろしくお願いします。

**Comment by yamauchi-inochu** [comment]
ライセンスに関する事項について、ご意見とご説明をいただきありがとうございます。  

ご指摘のとおり、現在の記載では、「著作権上許可されない利用が教育では許される」という誤解を生みかねませんので、該当箇所を修正いたします。  

本教材での著作物の利用は、適法引用にあたるとケースとして記載する方が正確かと思いましたので、関連する箇所についても修正を行いたいと思います。
