### ISSUE TITLE
textlintを使うプロジェクトへの追加依頼

### ISSUE THREAD

**Issue by kamataryo** [gis-oer/gis-oer#7]
こんにちは。
このプロジェクトがデモ段階の時に私がプルリクエストとして追加した文章校正プログラムの textlint ですが、その公式サイトがアップデートされていて、「textlintを使っているプロジェクト一覧」というページができていて、追加依頼ができます。
https://textlint.github.io/users.html

この「GIS実習オープン教材」プロジェクトを追加するように依頼してみてもいいですか？アイコンとリンクを表示してもらえると思います。

**Comment by yamauchi-inochu** [comment]
ご意見をいただき、ありがとうございます。textlintのサイトへの追加申請について、ぜひよろしくお願いいたします。

また、プルリクエストもいただき、ありがとございます。後ほどマージさせていただきます。

**Comment by kamataryo** [comment]
https://github.com/textlint/textlint/pull/523

**Comment by kamataryo** [comment]
マージされました。ユーザーページもそのうち更新されると思います！
![screenshot](https://user-images.githubusercontent.com/19714/40340670-2eddb93c-5dbb-11e8-813b-6d6de0e78ab4.png)
https://textlint.github.io/users.html

**Comment by yamauchi-inochu** [comment]
ご対応いただき、ありがとうございました。
