### ISSUE TITLE
テーブル結合について

### ISSUE THREAD

**Issue by tosseto** [gis-oer/gis-oer#8]
よくある質問とエラーに「テーブル結合」の説明がある（https://github.com/gis-oer/gis-oer/blob/master/materials/questions/questions.md）のですが，ベクタデータの作成・編集においてかなり多用される機能なので，例えば「空間データの統合・修正」（https://github.com/gis-oer/gis-oer/blob/master/materials/10/10.md）あたりに項目として入れるか，または，よくある質問とエラーの該当ページへのリンクを張ってはどうでしょうか．

**Comment by yamauchi-inochu** [comment]
対応が遅くなり、大変申し訳ありませんでした。テーブル結合については、[視覚的伝達](https://github.com/gis-oer/gis-oer/blob/master/materials/21/21.md#%E3%83%86%E3%83%BC%E3%83%96%E3%83%AB%E7%B5%90%E5%90%88)に移動しました。QGIS2.8による処理の解説は、よくある質問とエラーのページに残してあります。
